name: Send Daily Tech News

on:
  schedule:
    - cron: '0 0 * * *' # 每天UTC0点，北京时间8点
  workflow_dispatch:

jobs:
  send-news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests yagmail
      - name: Run script
        env:
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python send_top_tech_news.py